/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

//TODO disable auresizing

/*
 * NewPoll.java
 *
 * Created on 12-Oct-2010, 10:22:05
 */

package wevote_app;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import org.jdesktop.application.Action;

/**
 *
 * @author Hollgam
 */
public class NewPoll extends javax.swing.JFrame {

    public static boolean editStatePoll = false;
    public static int selectedLabel = 0;
    private int charactersUsed = 0;

    /** Creates new form NewPoll */
    public NewPoll() {
        initComponents();
        if (editStatePoll) {
            this.setTitle("Edit Poll");
            jButton3.setVisible(false);
            //System.out.println("EDIT");

            //TODO Disable add Button if topic Id is not vlid or Question name is wrong or there are no answers
            jTextField1.setText(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getQuestion()); //adding title of the topic to edit
            try {
                jTextField2.setText(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getAnswers().get(0)); //adding title of the topic to edit
            } catch (Exception e) {}
            try {
                jTextField3.setText(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getAnswers().get(1)); //adding title of the topic to edit
            } catch (Exception e) {}
            try {
                jTextField4.setText(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getAnswers().get(2)); //adding title of the topic to edit
            } catch (Exception e) {}
            try {
                jTextField5.setText(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getAnswers().get(3)); //adding title of the topic to edit
            } catch (Exception e) {}

            editStatePoll = false; // set back to creating New

        } else {
            this.setTitle("Create a new Poll");
            jButton2.setVisible(false);
            jButton4.setVisible(false);
        }
        jTextField9.setText("A.");
        jTextField10.setText("B.");
        jTextField11.setText("C.");
        jTextField8.setText("D.");
        String maxID = Integer.toString(Main.topicArray.size());
        jLabel12.setText("(Max ID: " + maxID + ")"); // setting max ID from the size of topicArray
        jTextField12.setText(Integer.toString(MainFrame.currentTopicID+1));

        jTextField1.addKeyListener(keyListener);
        jTextField2.addKeyListener(keyListener);
        jTextField3.addKeyListener(keyListener);
        jTextField4.addKeyListener(keyListener);
        jTextField5.addKeyListener(keyListener);

        charactersUsed=jTextField1.getText().length()+jTextField2.getText().length()+jTextField3.getText().length()+jTextField4.getText().length()+jTextField5.getText().length();
        if(jTextField2.getText().length() > 0) {
            charactersUsed+=3;
        }
        if(jTextField3.getText().length() > 0) {
            charactersUsed+=3;
        }
        if(jTextField4.getText().length() > 0) {
            charactersUsed+=3;
        }
        if(jTextField5.getText().length() > 0) {
            charactersUsed+=3;
        }

        charactersUsed++; //for > char
        jTextField6.setText(Integer.toString(charactersUsed));
        jTextField7.setText(Integer.toString(charactersUsed/160+1));

        this.getRootPane().setDefaultButton(jButton3);
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel9.setText("jLabel9");
        jLabel9.setName("jLabel9"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Poll");

        jLabel2.setText("Question");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Option 1");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Option 2");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Option 3");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Option 4");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Number of characters used:");
        jLabel7.setName("jLabel7"); // NOI18N

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLengthSMS(evt);
            }
        });
        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setName("jTextField2"); // NOI18N

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setName("jTextField3"); // NOI18N

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField4.setName("jTextField4"); // NOI18N

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField5.setName("jTextField5"); // NOI18N

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField6.setName("jTextField6"); // NOI18N

        jLabel8.setText("Number of text messages:");
        jLabel8.setName("jLabel8"); // NOI18N

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField7.setName("jTextField7"); // NOI18N

        jLabel10.setText("Options");
        jLabel10.setName("jLabel10"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A.B.C.D", "1.2.3.4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelHandler(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setName("jTextField8"); // NOI18N

        jTextField9.setEditable(false);
        jTextField9.setName("jTextField9"); // NOI18N

        jTextField10.setEditable(false);
        jTextField10.setName("jTextField10"); // NOI18N

        jTextField11.setEditable(false);
        jTextField11.setName("jTextField11"); // NOI18N

        jLabel11.setText("Topic");
        jLabel11.setName("jLabel11"); // NOI18N

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField12.setName("jTextField12"); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(NewPoll.class, this);
        jButton2.setAction(actionMap.get("deletePoll")); // NOI18N
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jButton2.setForeground(java.awt.Color.red);
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("newPoll")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton4.setAction(actionMap.get("editPoll")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jLabel12.setText("(Max ID: ");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setName("jLabel13"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextPane1.setText("Please add a Question and at least one Option."); // NOI18N
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setEnabled(false);
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField10)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                            .addComponent(jTextField11)
                                            .addComponent(jTextField8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jButton4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel13)
                    .addComponent(jButton2)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void labelHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelHandler
        selectedLabel = jComboBox1.getSelectedIndex();
        //System.out.println(selectedLabel);
        if (selectedLabel == 0) {
            jTextField9.setText("A.");
            jTextField10.setText("B.");
            jTextField11.setText("C.");
            jTextField8.setText("D.");
        } else if(selectedLabel == 1) {
            jTextField9.setText("1.");
            jTextField10.setText("2.");
            jTextField11.setText("3.");
            jTextField8.setText("4.");
        }
    }//GEN-LAST:event_labelHandler

    private void checkLengthSMS(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLengthSMS
        //System.out.println("EDIT");
    }//GEN-LAST:event_checkLengthSMS

    private void jTextField1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1CaretPositionChanged
        //System.out.println("DDD");
    }//GEN-LAST:event_jTextField1CaretPositionChanged


    KeyListener keyListener = new KeyListener() {
        public void keyPressed(KeyEvent keyEvent) {  
        }

        public void keyReleased(KeyEvent keyEvent) {
            charactersUsed=jTextField1.getText().length()+jTextField2.getText().length()+jTextField3.getText().length()+jTextField4.getText().length()+jTextField5.getText().length();
            if(jTextField2.getText().length() > 0) {
                charactersUsed+=3;
            }
            if(jTextField3.getText().length() > 0) {
                charactersUsed+=3;
            }
            if(jTextField4.getText().length() > 0) {
                charactersUsed+=3;
            }
            if(jTextField5.getText().length() > 0) {
                charactersUsed+=3;
            }

            charactersUsed++; //for > char
            jTextField6.setText(Integer.toString(charactersUsed));
            jTextField7.setText(Integer.toString(charactersUsed/160+1));

        }
        public void keyTyped(KeyEvent keyEvent) {     
        }
    };

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewPoll().setVisible(true);
//            }
//        });
//    }

    @Action
    public void newPoll() {
        ArrayList<String> answers = makeAnswerString();
        try {
            if (!jTextField12.getText().equals("")) {
                //check if there is TopicID entered
                int topicID = Integer.parseInt(jTextField12.getText());
                if ((topicID <= Main.topicArray.size() && topicID > 0) &&(!jTextField2.getText().equals("")) && (!jTextField1.getText().equals(""))) {
                    //check if topicID selected is valid adn if there is at least one answer and a name present
                    Main.addPoll(topicID, jTextField1.getText(), answers);
                    //System.out.println(answers);

                    //Main.frame.setDisabledElement(3);
                    Main.frame.setDisabledElement(4);
                    Main.frame.setDisabledElement(5);
                    this.setVisible(false);

                } else {
                    jLabel13.setText("Correct Fields!");
                }
            } else {
                jLabel13.setText("Correct Fields!");
            }
        } catch (NumberFormatException nFE) {
            //System.out.println("Not an Integer");
        }
    }

    private ArrayList<String> makeAnswerString() {
        //TODO add variation pointers (A. 1. ... )
        ArrayList<String> answers = new ArrayList<String>();
        if (!jTextField2.getText().equals("")) {
            String ansStr = jTextField9.getText() + jTextField2.getText();
            answers.add(ansStr);
        }
        if (!jTextField3.getText().equals("")) {
            String ansStr = jTextField10.getText() + jTextField3.getText();
            answers.add(ansStr);
        }
        if (!jTextField4.getText().equals("")) {
            String ansStr = jTextField11.getText() + jTextField4.getText();
            answers.add(ansStr);
        }
        if (!jTextField5.getText().equals("")) {
            String ansStr = jTextField8.getText() + jTextField5.getText();
            answers.add(ansStr);
        }
        //System.out.println(answers);
        return answers;
    }

    @Action
    public void editPoll() {
        Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).setQuestion(jTextField1.getText());
        ArrayList<String> answers = makeAnswerString();
        Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).setAnswers(answers);
        int newID =Integer.parseInt(jTextField12.getText()) - 1;
        //System.out.println("CUR " + MainFrame.currentTopicID);
        //System.out.println("NEW " + newID);


        if (newID!= MainFrame.currentTopicID) {
            //System.out.println("SIZE1 " + Main.topicArray.get(newID).getPollArrayList().size());
            Main.topicArray.get(newID).getPollArrayList().add(Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID)); // move poll to a new topic id needed
            Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().remove(MainFrame.currentPollID);
            //System.out.println("SIZE1 " + Main.topicArray.get(newID).getPollArrayList().size());
            //System.out.println("ADDED");
            //TODO make moving of poll work
        }

        Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).makeQuestionString();

        Main.frame.updateList2(MainFrame.currentTopicID);
        Main.frame.updateList1();
        String pollName = Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getQuestion();
        Main.frame.refreshLog("Poll \"" + pollName + "\" has been removed.");
       
        this.dispose();
    }

    @Action
    public void deletePoll() {
        String pollName = Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().get(MainFrame.currentPollID).getQuestion();
        Main.topicArray.get(MainFrame.currentTopicID).getPollArrayList().remove(MainFrame.currentPollID);

        //MainFrame.currentTopicID = 0;
        MainFrame.currentPollID = 0;
        Main.frame.updateList2(MainFrame.currentTopicID);
        Main.frame.updateList1();
        Main.frame.refreshLog("Poll \"" + pollName + "\" has been removed.");

        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
