/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewTopic.java
 *
 * Created on Oct 12, 2010, 2:40:45 PM
 */

package wevote_app;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.jdesktop.application.Action;

/**
 *
 * @author hollgam
 */
public class NewTopic extends javax.swing.JFrame {

    public static boolean editState = false;

    /** Creates new form NewTopic */
    public NewTopic() {
        initComponents();
        if (editState) {
            this.setTitle("Edit Topic");
            jButton1.setVisible(false);
            jTextField1.setText(Main.topicArray.get(MainFrame.currentTopicID).getTitle()); //adding title of the topic to edit
            editState = false; // set back to creating New

        } else {
            this.setTitle("Create a new Topic");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
        }
        this.getRootPane().setDefaultButton(jButton1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Topic");
        setResizable(false);

        jLabel1.setText("Title:");
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(NewTopic.class, this);
        jButton1.setAction(actionMap.get("createNewTopic")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("deleteTopic")); // NOI18N
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setForeground(java.awt.Color.red);
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("editTopic")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(64, 64, 64)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewTopic().setVisible(true);
//            }
//        });
//    }

    @Action
    public void createNewTopic() {
//        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
//            Date date = df.parse(jTextField2.getText());
//            //System.out.println("Date = " + df.format(date));
        if(!jTextField1.getText().isEmpty()) {
            Main.addTopic(jTextField1.getText());
            this.dispose();
        } else {
            jLabel2.setText("Correct fields!");
        }
        
    }

    @Action
    public void deleteTopic() {
        String topicName = Main.topicArray.get(MainFrame.currentTopicID).getTitle();
        //System.out.println(Main.topicArray.size());
        Main.topicArray.remove(MainFrame.currentTopicID);
        //System.out.println(Main.topicArray.size());
        
        MainFrame.currentTopicID = 0;
        MainFrame.currentPollID = 0;
        Main.frame.updateList1();
        Main.frame.clearList2();
        
        Main.frame.refreshLog("Topic \"" + topicName + "\" has been removed.");

        this.dispose();
    }

    @Action
    public void editTopic() {
        if (!jTextField1.getText().isEmpty()) {
           String topicName = Main.topicArray.get(MainFrame.currentTopicID).getTitle();
            Main.topicArray.get(MainFrame.currentTopicID).setTitle(jTextField1.getText());
    //        MainFrame.currentTopicID = 0;
    //        MainFrame.currentPollID = 0;
            Main.frame.updateList1();
            Main.frame.refreshLog("Topic \"" + topicName + "\" has been edited.");
    //        Main.frame.clearList2();
            this.dispose();
        } else {
            jLabel2.setText("Correct fields!");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
